#!/usr/bin/env bash
# This script changes localhost and facebook.com to custom IPs

cp /etc/hosts /etc/hosts.bak

echo "127.0.0.2 localhost" | sudo tee -a /etc/hosts
echo "8.8.8.8 facebook.com" | sudo tee -a /etc/hosts
